- src/api/cookie.js
Fix cookie callback
If there is an error, do not try and use response data
If there is no error, continue
@mickr @mcampa
> Fix cookie callback

- package.json
- src/tools/image.js
> MERC-962 Fix image tool to use strings

- src/api/cart.js
Adds a method to get the total quantity of items in the Cart using the [Storefront Cart API](https://developer-beta.bigcommerce.com/api-reference/cart-checkout/storefront-cart-api/cart/getcarts).
Adds up quantities across 3 types of product (physical, digital, custom) as well as a count of gift certificates in the cart to get the quantity.
Interested in feedback on approach from @bigcommerce/storefront-team and @bigcommerce/checkout 
Example usage:
utils.api.cart.getCart({}, (err, response) => {
console.log(response);
console.log(err);
});
utils.api.cart.getCart({includeOptions: true}, (err, response) => {
console.log(response);
console.log(err);
});
utils.api.cart.getCartQuantity(quantity => {
console.log(`Quantity: ${quantity}`);
});
> STRF-5628 - Add method to get cart quantity

- src/lib/request.js
@bigcommerce/storefront-team @bigcommerce/platform-engineering
> STRF-6013 Add csrf token header to all requests.

- package-lock.json
- package.json
Updating jQuery to latest version.
> chore(storefront): STRF-6720 Update jQuery to 3.4.1

- src/hooks/base.js
- src/hooks/cart.js
- src/hooks/currency-selector.js
- src/hooks/faceted-search.js
- src/hooks/product.js
- src/hooks/search.js
- src/hooks/sort-by.js
- src/lib/closest.js
- src/test-unit/closest.spec.js
Keeping jquery for ajax  and other methods have been switched to vanilla js. Making another ticket to remove ajax request from stencil-utils
> STRF-7025 remove jquery from stencil-utils

- src/api/cart.js
We'll continue to support requesting the "current cart" without an ID, but also allow accepting an explicit ID. This is unnecessary for now, but might be useful in the future.
⚠️ This is a breaking change, because originally `getCart` (singular) was in fact getting a collection of 1 cart. Now it correctly returns a single cart, but that breaks the interface so we should do a `5.0` for this change.
FYI @bigcommerce/storefront-team
> Accept cart ID to explicitly request a cart by ID

- src/api/product-attributes.js
Pressing on quick view, image changes not reflected
Add links to any relevant tickets and documentation.
- https://jira.bigcommerce.com/browse/STRF-8769
- https://jira.bigcommerce.com/browse/BCTHEME-295
> STRF-8769 Quick View - Image and price changes not reflected if an image is assigned to variant/sku

- .github/workflows/build.yml
> switch to github actions

- package.json
@bookernath @bigcommerce/storefront-team
> Bump stencil utils to 6.6.0

- package.json
Check please https://github.com/bigcommerce/cornerstone/pull/1920
> Bump stencil utils to 6.7.0

- src/api/cart.js
- Add method to fetch the less expensive "cart summary" endpoint
- Refactor cartQuantity method to use this new endpoint, to improve performance and reduce load
> Add method to use cart summary endpoint, refactor summary fetch

- package.json
> Release version 6.9.0

- src/lib/request.js
**What?**
This PR fix console errors. Errors appeared when сhanging options on Cart Page.
**Tickets / Documentation**
- [BCTHEME-510](https://jira.bigcommerce.com/browse/BCTHEME-510)
**Screenshots**
> fix(storefront): BCTHEME-510 Changing options on Cart Page causing console errors

- package.json
Bump version to release fix on using sections check during request
> Release 6.10

- spec/api.spec.js
- spec/wishlist.spec.js
- src/api/index.js
- src/api/wishlist.js
@bc-alexsaiannyi @yurytut1993 @jairo-bc 
This PR creates a method which will be responsible for adding an item to the wishlist.
[BCTHEME-466](https://jira.bigcommerce.com/browse/BCTHEME-466) - related ticket
> feat(storefront): BCTHEME-809 Create a method which will be responsible for adding an item to the wishlist.

- .github/workflows/release.yml
Github actions to release package
> STRF-9319 Github release

- .eslintrc
- .github/workflows/build.yml
- .gitignore
- package-lock.json
- package.json
- spec/api/cart.spec.js
- spec/api/countries.spec.js
- spec/api/index.spec.js
- spec/bodl/base.spec.js
- spec/bodl/cart.spec.js
- src/api/cart.js
- src/api/index.js
- src/bodl/base.js
- src/bodl/cart.js
Integrated Add/Remove Events and covered with tests
Refactored some tests structure
Updated workflow to support private repos
Silenced warnings on func-names
cc @bigcommerce/storefront-team
> feat: STRF-9846 Integrate Bodl Events for Cart Add/Remove

- package.json
-   feat: STRF-9846 Integrate Bodl Events for Cart Add/Remove ([167](https://github.com/bigcommerce/stencil-utils/pull/167))
-   feat: STRF-9982 Use BODL events from global scope ([171](https://github.com/bigcommerce/stencil-utils/pull/171))
> chore: release 6.12.0

- package-lock.json
- package.json
- spec/api/cart.spec.js
- src/api/cart.js
1) Wrapped bodl calls with callbacks to corresponding ajax calls (add and remove)
2) Covered cases with unit tests
cc @bigcommerce/storefront-team
> fix: STRF-10066 Fix add to cart button

- package.json
- fix STRF-10066: Fix add to cart button
> chore: release 6.12.1

- package-lock.json
- package.json
- bump webpack and dependencies
- bump bodl events to 1.9.0
cc @bigcommerce/storefront-team
> feat: STRF-10366 Webpack 5

- package-lock.json
- package.json
Rename cart_value to product_value for BODL Cart events
> chore: DATA-10695 release 6.15.0

- package.json
- Add `event_id` field for BODL events
- Change `product_id` field type to string
> chore(analytics): DATA-11047 Release 6.16.0

- package.json
> chore: release 6.17.0

- src/api/cart.js
Add `updateCartItemOptions` to stencil utils to ensure there is easier developer adoption with AJAX calls to update cart items from the cart page.
Roll back this PR
Tested locally
cc @bigcommerce/team-storefront 
[STRF-12475]: https://bigcommercecloud.atlassian.net/browse/STRF-12475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> STRF-12475: Add postFormData for cart.php to stencil-utils

- package.json
Version bump
Revert
Locally
[STRF-12475]: https://bigcommercecloud.atlassian.net/browse/STRF-12475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> STRF-12475: Update version

- package-lock.json
- package.json
* Cancel Quick Search Requests Early if New Search is Started - ([#221](https://github.com/bigcommerce/stencil-utils/pull/221))
> chore: release 6.20.0
